apiVersion: v1
kind: Secret
metadata:
  name: repo-access
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: ${REPO_URL}
  password: ${GITHUB_TOKEN}
  username: git
