kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  extraPortMappings:
  - containerPort: 30080
    hostPort: ${HOST_PORT}
    protocol: TCP
networking:
  apiServerAddress: "127.0.0.1"
kubeadmConfigPatches:
  - |
    kind: ClusterConfiguration
    apiServer:
      certSANs:
        - "${CLUSTER_NAME}-control-plane"
        - "127.0.0.1"
        - "localhost"
